name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build image
        run: |
          echo "Building version ${{ github.run_id }}"
          docker build -t ${{ secrets.DOCKERHUB_REGISTRY }}/${{ github.event.repository.name }}:${{ github.run_id }} .

      - name: Push image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_REGISTRY }}/${{ github.event.repository.name }}:${{ github.run_id }}

      - name: Tag and push as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_REGISTRY }}/${{ github.event.repository.name }}:${{ github.run_id }} ${{ secrets.DOCKERHUB_REGISTRY }}/${{ github.event.repository.name }}:latest
          docker push ${{ secrets.DOCKERHUB_REGISTRY }}/${{ github.event.repository.name }}:latest
